// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxInbuX5RagRk4Z0we62sqcm0D9QbScts',
    appId: '1:1002398347351:web:3567c0f780ebd1fc517312',
    messagingSenderId: '1002398347351',
    projectId: 'messaing-notification',
    authDomain: 'messaing-notification.firebaseapp.com',
    storageBucket: 'messaing-notification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaKLjS_Nqq74Y0Qy41aD-hIJmivS-BBaE',
    appId: '1:1002398347351:android:fc2a8e86496fff13517312',
    messagingSenderId: '1002398347351',
    projectId: 'messaing-notification',
    storageBucket: 'messaing-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0WP2yJeb62i1oJPyawsNljD9ODEK-x4',
    appId: '1:1002398347351:ios:490905690e0de395517312',
    messagingSenderId: '1002398347351',
    projectId: 'messaing-notification',
    storageBucket: 'messaing-notification.appspot.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH0WP2yJeb62i1oJPyawsNljD9ODEK-x4',
    appId: '1:1002398347351:ios:490905690e0de395517312',
    messagingSenderId: '1002398347351',
    projectId: 'messaing-notification',
    storageBucket: 'messaing-notification.appspot.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxInbuX5RagRk4Z0we62sqcm0D9QbScts',
    appId: '1:1002398347351:web:fcaef21036fd8ff9517312',
    messagingSenderId: '1002398347351',
    projectId: 'messaing-notification',
    authDomain: 'messaing-notification.firebaseapp.com',
    storageBucket: 'messaing-notification.appspot.com',
  );
}
