// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxdT2vo4Fl-bsoopwmGljuDUCx-eIOl1k',
    appId: '1:164211546185:web:8ecb5bea61401888c74798',
    messagingSenderId: '164211546185',
    projectId: 'local-notification-token',
    authDomain: 'local-notification-token.firebaseapp.com',
    storageBucket: 'local-notification-token.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Ks6gBr8nc8XNXlcmIMFOcgkmFzY4JTs',
    appId: '1:164211546185:android:93484a1066fd1c38c74798',
    messagingSenderId: '164211546185',
    projectId: 'local-notification-token',
    storageBucket: 'local-notification-token.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY19NAAmDhTNJ2SSx00Pup5DRABSITC8Y',
    appId: '1:164211546185:ios:297502b15290cffec74798',
    messagingSenderId: '164211546185',
    projectId: 'local-notification-token',
    storageBucket: 'local-notification-token.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY19NAAmDhTNJ2SSx00Pup5DRABSITC8Y',
    appId: '1:164211546185:ios:297502b15290cffec74798',
    messagingSenderId: '164211546185',
    projectId: 'local-notification-token',
    storageBucket: 'local-notification-token.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxdT2vo4Fl-bsoopwmGljuDUCx-eIOl1k',
    appId: '1:164211546185:web:e083857f1b69bbe9c74798',
    messagingSenderId: '164211546185',
    projectId: 'local-notification-token',
    authDomain: 'local-notification-token.firebaseapp.com',
    storageBucket: 'local-notification-token.appspot.com',
  );
}
